/*
  Outputs
  Develop By: William MR
*/

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks-cluster.kubeconfig
}

output "external-dns-policy-arn" {
  description = "EKS External DNS Policy ARN"
  value       = aws_iam_policy.policy.arn
}