version: 2.1

terraform: &terraform
  working_directory: ~/repo
  docker:
    - image: hashicorp/terraform:0.12.29
  environment:
    TF_IN_AUTOMATION: true
    TF_VAR_AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    TF_VAR_AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    TF_VAR_AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

jobs:
  init:
    <<: *terraform
    steps:
      - checkout
      - run:
          name: init
          command: terraform init
      - persist_to_workspace:
          root: ~/repo
          paths: .

  plan:
    <<: *terraform
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: plan
          command: terraform plan
      - store_artifacts:
          path: ~/repo/tfplan
          destination: tfplan
      - persist_to_workspace:
          root: ~/repo
          paths: .

  apply:
    <<: *terraform
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: apply
          command: terraform apply -auto-approve
      - run:
          name: show
          command: terraform show -no-color > tfresult
      - store_artifacts:
          path: ~/repo/tfresult
          destination: tfresult            

  destroy:
    <<: *terraform
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: destroy app
          command: terraform destroy -auto-approve

workflows:
  version: 2
  build_deploy:
    jobs:
      - init
      - plan:
          requires:
            - init
      - apply:
          requires:
            - plan
          filters:
            branches:
              only:
                - master
      - destroy:
          requires:
            - plan
          filters:
            branches:
              only:
                - destroy
